package demo:demo;

interface transformer {
  transform: async func(in: stream<string>) -> stream<string>;
}

world top {
  include wasi:cli/command@0.3.0;
  import transformer;
}

world middle {
  import transformer;
  export transformer;
}

world bottom {
  export transformer;
}
